baseURL = "https://www.joseferben.com"
languageCode = "en-us"
title = "Josef's Blog"
paginate = 20
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics = "G-JHGX0765SG"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Josef's Blog"
description = "A blog about programming, creating things and philosophy."
keywords =["Programming", "Entrepreneurship", "Gaming", "Philosophy", "Blog", "Portfolio"]
showtoc = false
ShowPostNavLinks = true
author = "Josef Erben"
ShowCodeCopyButtons = true
ShowShareButtons = true
ShowReadingTime = true
comments = true
defaultTheme = "light"
disableThemeToggle = true

[params.assets]
disableHLJS = false
favicon = "/favicon/favicon-96x96.ico"
favicon16x16 = "/favicon/favicon-16x16.ico"
favicon32x32 = "/favicon/favicon-32x32.ico"
apple_touch_icon = "/favicon/apple-touch-icon-180x180.png"
safari_pinned_tab = "/favicon/apple-touch-icon-180x180.png"

[params.label]
iconHeight = 95

[params.homeInfoparams]
Title = "Hi there \U0001F44B"
content = "I am Josef and these are my personal notes disguised as blog posts. Here and there you might find an actual blog post. I like to [create](/tags/project/) things."

[[params.socialIcons]]
name = "github"
url = "https://github.com/joseferben"
[[params.socialIcons]]
name = "discord"
url = "https://discord.com/users/490443650623471617"
[[params.socialIcons]]
name = "twitch"
url = "https://twitch.tv/joseferben"
[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/joseferben"
[[params.socialIcons]]
name = "email"
url = "mailto:josef@erben.io"
[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/josef-erben-90a002b1/"

[params.analytics.google]
SiteVerificationTag = "G-JHGX0765SG"

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/tags/project/"
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"

[outputs]
home = ["HTML", "RSS", "JSON"]
